### ISSUE TITLE
swift package build error.   ?????

### ISSUE THREAD

**Issue by CoderLineChan** [robbiehanson/CocoaAsyncSocket#727]
1.swift package init
2. Edit the package.swift
let package = Package(
    name: "AsyncSocket",
    products: [
        // Products define the executables and libraries produced by a package, and make them visible to other packages.
        .library(
            name: "AsyncSocket",
            targets: ["AsyncSocket"]),
    ],
    dependencies: [
        .package(url: "https://github.com/robbiehanson/CocoaAsyncSocket", from: "7.6.4"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "AsyncSocket",
            dependencies: ["CocoaAsyncSocket"]),
    ]
)
3.swift build  (succeed!)
4.swift package generate-xcodeproj
5.open the xcodeproj  and build error.  
(xcode version 11.5 , swift version 5.2.4)
<img width="1055" alt="截屏2020-07-04 13 44 41" src="https://user-images.githubusercontent.com/21659158/86505903-a8d28a80-bdfc-11ea-9a3d-469d184c60b6.png">
<img width="794" alt="截屏2020-07-04 13 45 14" src="https://user-images.githubusercontent.com/21659158/86505904-abcd7b00-bdfc-11ea-8497-d10de6c66853.png">

**Comment by CoderLineChan** [comment]
**## error message:**
Ld /Users/chenlianchen/Library/Developer/Xcode/DerivedData/AsyncSocket-fopqzpqwmrpvkveptlupoqhhhnwv/Build/Products/Debug/CocoaAsyncSocket.framework/Versions/A/CocoaAsyncSocket normal x86_64 (in target 'CocoaAsyncSocket' from project 'AsyncSocket')
    cd /Users/chenlianchen/Desktop/AsyncSocket

Undefined symbols for architecture x86_64:
  "_SSLClose", referenced from:
      -[GCDAsyncSocket closeWithError:] in GCDAsyncSocket.o
  "_SSLCopyPeerTrust", referenced from:
      -[GCDAsyncSocket ssl_continueSSLHandshake] in GCDAsyncSocket.o
  "_SSLCreateContext", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLGetBufferedReadSize", referenced from:
      ___33-[GCDAsyncSocket flushSSLBuffers]_block_invoke in GCDAsyncSocket.o
      -[GCDAsyncSocket doReadData] in GCDAsyncSocket.o
.......
"_kCFStreamSSLValidatesCertificateChain", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by largosblade** [comment]
I'm having the exact same problem. Will not compile from Xcode 11.5 But if I compile from command line using `swift build` then I'm an able to compile and run.

Here is the error from Xcode

```
Undefined symbols for architecture x86_64:
  "_SSLClose", referenced from:
      -[GCDAsyncSocket closeWithError:] in GCDAsyncSocket.o
  "_SSLCopyPeerTrust", referenced from:
      -[GCDAsyncSocket ssl_continueSSLHandshake] in GCDAsyncSocket.o
  "_SSLCreateContext", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLGetBufferedReadSize", referenced from:
      ___33-[GCDAsyncSocket flushSSLBuffers]_block_invoke in GCDAsyncSocket.o
      -[GCDAsyncSocket doReadData] in GCDAsyncSocket.o
  "_SSLHandshake", referenced from:
      -[GCDAsyncSocket ssl_continueSSLHandshake] in GCDAsyncSocket.o
  "_SSLRead", referenced from:
      -[GCDAsyncSocket flushSSLBuffers] in GCDAsyncSocket.o
      -[GCDAsyncSocket doReadData] in GCDAsyncSocket.o
  "_SSLSetCertificate", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetConnection", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetDiffieHellmanParams", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetEnabledCiphers", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetIOFuncs", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetPeerDomainName", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetPeerID", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetProtocolVersionMax", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetProtocolVersionMin", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLSetSessionOption", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_SSLWrite", referenced from:
      -[GCDAsyncSocket doWriteData] in GCDAsyncSocket.o
  "_kCFStreamSSLAllowsAnyRoot", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_kCFStreamSSLAllowsExpiredCertificates", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_kCFStreamSSLAllowsExpiredRoots", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_kCFStreamSSLCertificates", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_kCFStreamSSLIsServer", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_kCFStreamSSLLevel", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_kCFStreamSSLPeerName", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
  "_kCFStreamSSLValidatesCertificateChain", referenced from:
      -[GCDAsyncSocket ssl_startTLS] in GCDAsyncSocket.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by CoderLineChan** [comment]
YES！ I compile from command line using swift build then I'm an able to compile and run.
but，What compiler management do you use at the development stage？
I manage it with Xcode，and compilation error！

**Comment by japanese-goblinn** [comment]
Same error for me on `macOS 10.15.6`

**Comment by wlisac** [comment]
I'm also seeing this error on macOS 10.15.6 and Xcode 11.7.

`swift build` works as expected, but Xcode fails when attempting to build the generated project.

I'm seeing this error when attempting to use CocoaMQTT via SPM support introduced in https://github.com/emqx/CocoaMQTT/pull/322.
